### ISSUE TITLE
Where can I find the usage documentation for this, and how can I deploy and test my own PCB

### ISSUE THREAD

**Issue by FantasyGmm** [SlimeVR/Nighty-Hardware-Tester#16]
I have successfully compiled the tester on my arm64's SBC and pulled the Docker image
I drew my own PCB and wanted to use it to test them, but I couldn't find a way to use it on the wiki

**Comment by TheDevMinerTV** [comment]
Hi!

Please contact us in our [Discord](https://discord.gg/slimevr) in the development channels.

We will soon write documentation.
