### ISSUE TITLE
Backend should highlight errored out tests

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/Nighty-Hardware-Tester#7]
Test results that have errors or warnings should be highlighted in red or yellow on the results test page.

**Comment by TheDevMinerTV** [comment]
Implemented in https://github.com/SlimeVR/Nighty-Hardware-Tester/commit/1540d6da47216a1a44d525735cbd29e8f3dca433

**Comment by Eirenliel** [comment]
❤️
